import type { Problem } from "./types";

export const problems: Problem[] = [
  {
    id: "closed-ron-shanpon-triplet",
    title: "Closed ron completing a triplet",
    tags: ["closed ron", "shanpon", "value pair", "ron triplet"],
    hand: {
      concealedTiles: ["2m", "3m", "4m", "6p", "7p", "8p", "3s", "3s", "3s", "E", "E", "5m", "5m"],
      melds: [],
      winningTile: "5m",
      seatWind: "east",
      roundWind: "south",
      winMethod: "ron",
      riichi: true,
      doraIndicators: ["4p"],
      uraDoraIndicators: ["9s"],
    },
    answer: {
      han: 1,
      fu: 40,
      points: "2000",
      limitTier: "none",
      yaku: [{ name: "Riichi", han: 1 }],
      fuBreakdown: [
        { name: "Base fu", fu: 20, category: "base" },
        { name: "Closed ron", fu: 10, category: "hand" },
        { name: "Simple triplet completed by ron", fu: 2, category: "group" },
        { name: "Value pair: seat wind east", fu: 2, category: "group" },
        { name: "Rounded up to 40 fu", fu: 6, category: "rounding" },
      ],
    },
  },
  {
    id: "open-yakuhai-terminal-triplet",
    title: "Open hand with terminal triplet",
    tags: ["open hand", "yakuhai", "terminal triplet"],
    hand: {
      concealedTiles: ["2m", "3m", "4m", "4p", "5p", "6p", "7s", "8s", "9s", "9m"],
      melds: [{ type: "pon", tiles: ["P", "P", "P"], open: true, calledTile: "P" }],
      winningTile: "9m",
      seatWind: "south",
      roundWind: "east",
      winMethod: "ron",
      riichi: false,
      doraIndicators: ["3p"],
    },
    answer: {
      han: 2,
      fu: 30,
      points: "2000",
      limitTier: "none",
      yaku: [
        { name: "Yakuhai: white dragon", han: 1 },
        { name: "Dora", han: 1 },
      ],
      fuBreakdown: [
        { name: "Base fu", fu: 20, category: "base" },
        { name: "Open dragon triplet", fu: 4, category: "group" },
        { name: "Terminal pair wait", fu: 2, category: "wait" },
        { name: "Rounded up to 30 fu", fu: 4, category: "rounding" },
      ],
    },
  },
  {
    id: "pinfu-tsumo",
    title: "Pinfu tsumo",
    tags: ["pinfu", "tsumo", "no-points hand"],
    hand: {
      concealedTiles: ["2m", "3m", "4m", "3p", "4p", "5p", "6s", "7s", "8s", "6m", "6m", "3s", "4s"],
      melds: [],
      winningTile: "5s",
      seatWind: "west",
      roundWind: "east",
      winMethod: "tsumo",
      riichi: true,
      doraIndicators: ["9m"],
      uraDoraIndicators: ["1p"],
    },
    answer: {
      han: 3,
      fu: 20,
      points: "700/1300",
      limitTier: "none",
      yaku: [
        { name: "Riichi", han: 1 },
        { name: "Menzen tsumo", han: 1 },
        { name: "Pinfu", han: 1 },
      ],
      fuBreakdown: [
        { name: "Pinfu tsumo is scored as 20 fu", fu: 20, category: "base" },
      ],
    },
  },
  {
    id: "chiitoitsu",
    title: "Seven pairs",
    tags: ["chiitoitsu", "fixed fu"],
    hand: {
      concealedTiles: ["1m", "1m", "3m", "3m", "5p", "5p", "7p", "7p", "2s", "2s", "N", "N", "C"],
      melds: [],
      winningTile: "C",
      seatWind: "south",
      roundWind: "south",
      winMethod: "ron",
      riichi: true,
      doraIndicators: ["4p"],
      uraDoraIndicators: ["6s"],
    },
    answer: {
      han: 3,
      fu: 25,
      points: "4800",
      limitTier: "none",
      yaku: [
        { name: "Riichi", han: 1 },
        { name: "Chiitoitsu", han: 2 },
      ],
      fuBreakdown: [
        { name: "Chiitoitsu fixed value", fu: 25, category: "hand" },
      ],
    },
  },
  {
    id: "mangan-shortcut",
    title: "Mangan shortcut",
    tags: ["mangan", "limit hand", "dora"],
    hand: {
      concealedTiles: ["2m", "3m", "4m", "4m", "5m", "6m", "3p", "4p", "5p", "6s", "7s", "8s", "P"],
      melds: [],
      winningTile: "P",
      seatWind: "north",
      roundWind: "east",
      winMethod: "ron",
      riichi: true,
      doraIndicators: ["2p", "5s", "1m"],
      uraDoraIndicators: ["7s"],
    },
    answer: {
      han: 5,
      fu: 30,
      points: "8000",
      limitTier: "mangan",
      yaku: [
        { name: "Riichi", han: 1 },
        { name: "Yakuhai: white dragon", han: 1 },
        { name: "Dora", han: 3 },
      ],
      fuBreakdown: [
        { name: "Base fu", fu: 20, category: "base" },
        { name: "Pair wait", fu: 2, category: "wait" },
        { name: "Rounded up to 30 fu", fu: 8, category: "rounding" },
      ],
    },
  },
  {
    id: "haneman-shortcut",
    title: "Haneman shortcut",
    tags: ["haneman", "limit hand", "honitsu"],
    hand: {
      concealedTiles: ["2p", "3p", "4p", "5p", "6p", "7p", "8p", "8p", "8p", "E", "E", "P", "P"],
      melds: [],
      winningTile: "P",
      seatWind: "east",
      roundWind: "east",
      winMethod: "tsumo",
      riichi: true,
      doraIndicators: ["4p", "5p"],
      uraDoraIndicators: ["N", "3p"],
    },
    answer: {
      han: 6,
      fu: 40,
      points: "6000 all",
      limitTier: "haneman",
      yaku: [
        { name: "Riichi", han: 1 },
        { name: "Menzen honitsu", han: 3 },
        { name: "Dora", han: 2 },
      ],
      fuBreakdown: [
        { name: "Limit hand: fu does not change the haneman score", fu: 0, category: "hand" },
      ],
    },
  },
];
